---
 - hosts: linux
   remote_user: ansadm
   become: true
   tasks:
    - name: Create user wit ssh keys
      user: 
       name: ansssh
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa

